<?php

namespace App\Http\Middleware;

use App\Models\User;
use App\Services\UserNotificationService;
use App\Support\CustomerContext;
use Illuminate\Http\Request;
use Inertia\Middleware;

class HandleInertiaRequests extends Middleware
{
    protected $rootView = 'app';

    public function __construct(
        private readonly CustomerContext $customerContext,
        private readonly UserNotificationService $notificationService,
    ) {
    }

    public function version(Request $request): ?string
    {
        return parent::version($request);
    }

    public function share(Request $request): array
    {
        $user = $request->user();
        $customer = $this->customerContext->currentCustomer($user instanceof User ? $user : null);
        $department = $user instanceof User && $user->relationLoaded('primaryDepartment')
            ? $user->primaryDepartment
            : ($user instanceof User ? $user->primaryDepartment()->first() : null);

        return array_merge(parent::share($request), [
            'appName' => config('app.name'),
            'locale' => app()->getLocale(),
            'auth' => [
                'user' => $user instanceof User ? [
                    'id' => $user->id,
                    'name' => $user->name,
                    'email' => $user->email,
                    'role' => $user->role,
                    'bid_role' => $user->resolvedBidRole(),
                    'bid_role_label' => $user->bid_role_label,
                    'bid_manager_scope' => $user->resolvedBidManagerScope(),
                    'bid_manager_scope_label' => $user->bid_manager_scope_label,
                    'primary_affiliation_scope' => $user->resolvedPrimaryAffiliationScope(),
                    'primary_affiliation_scope_label' => $user->primary_affiliation_scope_label,
                    'is_system_owner' => $user->isSystemOwner(),
                    'is_bid_manager' => $user->isBidManager(),
                    'can_manage_customer_billing' => $user->canManageCustomerBilling(),
                    'can_manage_customer_users' => $this->customerContext->canManageCustomerUsers($user),
                    'can_manage_customer_departments' => $this->customerContext->canCreateCustomerDepartments($user),
                    'can_manage_watch_profiles' => $user->canAccessCustomerFrontend(),
                    'can_manage_department_watch_profiles' => $this->customerContext->isCustomerAdmin($user) || $this->customerContext->hasDepartmentMembership($user),
                    'customer' => $customer ? [
                        'id' => $customer->id,
                        'name' => $customer->name,
                    ] : null,
                    'department' => $department ? [
                        'id' => $department->id,
                        'name' => $department->name,
                    ] : null,
                ] : null,
            ],
            'notifications' => $user instanceof User
                ? $this->notificationService->panelPayload($user)
                : null,
            'flash' => [
                'success' => fn (): ?string => $request->session()->get('success'),
                'error' => fn (): ?string => $request->session()->get('error'),
                'userCreated' => fn (): ?array => $request->session()->get('userCreated'),
                'retrievalTest' => fn (): ?array => $request->session()->get('retrievalTest'),
            ],
            'translations' => [
                'navigation' => [
                    'bid_status' => __('procynia.navigation.bid_status'),
                    'notices' => __('procynia.navigation.notices'),
                    'ai' => __('procynia.navigation.ai'),
                    'competitors' => __('procynia.navigation.competitors'),
                    'watch_lists' => __('procynia.navigation.watch_lists'),
                    'customer_environment' => __('procynia.navigation.customer_environment'),
                    'overview' => __('procynia.navigation.overview'),
                    'worklist' => __('procynia.navigation.worklist'),
                    'ai_instructions' => __('procynia.navigation.ai_instructions'),
                    'company_vocabulary' => __('procynia.navigation.company_vocabulary'),
                    'knowledge_documents' => __('procynia.navigation.knowledge_documents'),
                    'live_search' => __('procynia.navigation.live_search'),
                    'registered_notices' => __('procynia.navigation.registered_notices'),
                    'history' => __('procynia.navigation.history'),
                ],
                'dashboard' => __('procynia.dashboard'),
                'notices' => __('procynia.notices'),
                'ai' => __('procynia.ai'),
                'knowledge' => __('procynia.knowledge'),
                'saved_notice' => __('procynia.saved_notice'),
                'billing' => __('procynia.billing'),
                'user' => __('procynia.user'),
                'suppliers' => __('procynia.suppliers'),
                'customer_env' => __('procynia.customer_env'),
                'info_center_page' => __('procynia.info_center_page'),
                'watch_profile_page' => __('procynia.watch_profile_page'),
                'common' => [
                    'back' => __('procynia.frontend.back'),
                    'cancel' => __('procynia.common.cancel'),
                    'customer' => __('procynia.common.customer'),
                    'deadline' => __('procynia.notice.deadline'),
                    'download' => __('procynia.frontend.download'),
                    'loading' => __('procynia.frontend.loading'),
                    'next' => __('procynia.frontend.next'),
                    'not_available' => __('procynia.common.not_available'),
                    'logout' => __('procynia.frontend.logout'),
                    'none' => __('procynia.common.none'),
                    'notice' => __('procynia.notice.resource'),
                    'notices' => __('procynia.frontend.notices_nav'),
                    'open' => __('procynia.frontend.open'),
                    'previous' => __('procynia.frontend.previous'),
                    'published' => __('procynia.notice.publication_date'),
                    'search' => __('procynia.frontend.search'),
                    'status' => __('procynia.notice.status'),
                ],
                'frontend' => [
                    'all' => __('procynia.frontend.all'),
                    'alert_settings' => __('procynia.frontend.alert_settings'),
                    'alert_summary' => __('procynia.frontend.alert_summary'),
                    'alerts_monitoring_title' => __('procynia.frontend.alerts_monitoring_title'),
                    'alerts_nav' => __('procynia.frontend.alerts_nav'),
                    'apply_filters' => __('procynia.frontend.apply_filters'),
                    'buyer' => __('procynia.frontend.buyer'),
                    'clear_filters' => __('procynia.frontend.clear_filters'),
                    'customer_area' => __('procynia.frontend.customer_area'),
                    'customer_footer' => __('procynia.frontend.customer_footer'),
                    'customer_safe_reasoning' => __('procynia.frontend.customer_safe_reasoning'),
                    'deadline_expired' => __('procynia.frontend.deadline_expired'),
                    'deadline_open' => __('procynia.frontend.deadline_open'),
                    'department' => __('procynia.common.department'),
                    'document_count' => __('procynia.frontend.document_count'),
                    'documents' => __('procynia.frontend.documents'),
                    'download' => __('procynia.frontend.download'),
                    'download_all' => __('procynia.frontend.download_all'),
                    'download_all_failed' => __('procynia.frontend.download_all_failed'),
                    'empty' => __('procynia.frontend.empty_state'),
                    'empty_list_title' => __('procynia.frontend.empty_list_title'),
                    'file_size' => __('procynia.frontend.file_size'),
                    'file_type' => __('procynia.frontend.file_type'),
                    'filters_title' => __('procynia.frontend.filters_title'),
                    'go_to_worklist' => __('procynia.frontend.go_to_worklist'),
                    'keyword' => __('procynia.frontend.keyword'),
                    'matched_for_customer' => __('procynia.frontend.matched_for_customer'),
                    'new_hits_last_day' => __('procynia.frontend.new_hits_last_day'),
                    'no_department_context' => __('procynia.frontend.no_department_context'),
                    'no_documents' => __('procynia.frontend.no_documents'),
                    'notice_list_title' => __('procynia.frontend.notice_list_title'),
                    'notice_detail_title' => __('procynia.frontend.notice_detail_title'),
                    'notice_source_attention' => __('procynia.frontend.notice_source_attention'),
                    'notice_reference' => __('procynia.frontend.notice_reference'),
                    'open_button' => __('procynia.frontend.open_button'),
                    'open_notice' => __('procynia.frontend.open_notice'),
                    'organization_name' => __('procynia.frontend.organization_name'),
                    'overview_nav' => __('procynia.frontend.overview_nav'),
                    'infosenter_nav' => __('procynia.frontend.infosenter_nav'),
                    'published' => __('procynia.notice.publication_date'),
                    'procurements_nav' => __('procynia.frontend.procurements_nav'),
                    'procurements_subtitle' => __('procynia.frontend.procurements_subtitle'),
                    'publish_date' => __('procynia.frontend.publish_date'),
                    'reason_customer_match' => __('procynia.frontend.reason_customer_match'),
                    'reason_watch_profile' => __('procynia.frontend.reason_watch_profile'),
                    'relevance' => __('procynia.notice.relevance_level'),
                    'relevance_score' => __('procynia.frontend.relevance_score'),
                    'relevant_for_departments' => __('procynia.frontend.relevant_for_departments'),
                    'save_button' => __('procynia.frontend.save_button'),
                    'saved_searches_nav' => __('procynia.frontend.saved_searches_nav'),
                    'saved_searches_title' => __('procynia.frontend.saved_searches_title'),
                    'search_button' => __('procynia.frontend.search_button'),
                    'search_placeholder' => __('procynia.frontend.search_placeholder'),
                    'see_all' => __('procynia.frontend.see_all'),
                    'source_of_truth' => __('procynia.frontend.source_of_truth'),
                    'status' => __('procynia.notice.status'),
                    'sort_by' => __('procynia.frontend.sort_by'),
                    'support_mode_customer' => __('procynia.frontend.support_mode_customer'),
                    'support_mode_label' => __('procynia.frontend.support_mode_label'),
                    'tenant_safe' => __('procynia.frontend.tenant_safe_notice'),
                    'tenant_safe_notice' => __('procynia.frontend.tenant_safe_notice'),
                    'worklist_nav' => __('procynia.frontend.worklist_nav'),
                    'worklist_title' => __('procynia.frontend.worklist_title'),
                    'watch_profile' => __('procynia.common.watch_profile'),
                    'next_update' => __('procynia.frontend.next_update'),
                    'notice_status_all' => __('procynia.frontend.notice_status_all'),
                    'notice_status_active' => __('procynia.frontend.notice_status_active'),
                    'notice_status_expired' => __('procynia.frontend.notice_status_expired'),
                    'notice_status_awarded' => __('procynia.frontend.notice_status_awarded'),
                    'notice_status_cancelled' => __('procynia.frontend.notice_status_cancelled'),
                    'relevance_all' => __('procynia.frontend.relevance_all'),
                    'relevance_high' => __('procynia.frontend.relevance_high'),
                    'relevance_medium' => __('procynia.frontend.relevance_medium'),
                    'relevance_low' => __('procynia.frontend.relevance_low'),
                    'bid_status_all' => __('procynia.frontend.bid_status_all'),
                    'bid_status_discovered' => __('procynia.frontend.bid_status_discovered'),
                    'bid_status_qualifying' => __('procynia.frontend.bid_status_qualifying'),
                    'bid_status_go_no_go' => __('procynia.frontend.bid_status_go_no_go'),
                    'bid_status_in_progress' => __('procynia.frontend.bid_status_in_progress'),
                    'bid_status_submitted' => __('procynia.frontend.bid_status_submitted'),
                    'bid_status_negotiation' => __('procynia.frontend.bid_status_negotiation'),
                    'bid_status_won' => __('procynia.frontend.bid_status_won'),
                    'bid_status_lost' => __('procynia.frontend.bid_status_lost'),
                    'bid_status_no_go' => __('procynia.frontend.bid_status_no_go'),
                    'bid_status_withdrawn' => __('procynia.frontend.bid_status_withdrawn'),
                    'bid_status_archived' => __('procynia.frontend.bid_status_archived'),
                ],
                'public' => [
                    'nav' => [
                        'features' => __('procynia.public.nav.features'),
                        'pricing' => __('procynia.public.nav.pricing'),
                        'security' => __('procynia.public.nav.security'),
                        'contact' => __('procynia.public.nav.contact'),
                        'register' => __('procynia.public.nav.register'),
                    ],
                    'footer' => [
                        'privacy' => __('procynia.public.footer.privacy'),
                        'terms' => __('procynia.public.footer.terms'),
                        'contact_label' => __('procynia.public.footer.contact_label'),
                        'company_note' => __('procynia.public.footer.company_note'),
                    ],
                    'contactDetails' => config('procynia.public.contact'),
                    'home' => [
                        'title' => __('procynia.public.home.title'),
                        'lead' => __('procynia.public.home.lead'),
                        'point_company_only' => __('procynia.public.home.point_company_only'),
                        'point_direct_login' => __('procynia.public.home.point_direct_login'),
                        'point_setup_after' => __('procynia.public.home.point_setup_after'),
                        'point_ai_after_activation' => __('procynia.public.home.point_ai_after_activation'),
                        'panel_title' => __('procynia.public.home.panel_title'),
                        'panel_body' => __('procynia.public.home.panel_body'),
                        'panel_note' => __('procynia.public.home.panel_note'),
                        'cta_features' => __('procynia.public.home.cta_features'),
                        'cta_register' => __('procynia.public.home.cta_register'),
                    ],
                    'features' => [
                        'title' => __('procynia.public.features.title'),
                        'lead' => __('procynia.public.features.lead'),
                        'card_1_title' => __('procynia.public.features.card_1_title'),
                        'card_1_body' => __('procynia.public.features.card_1_body'),
                        'card_2_title' => __('procynia.public.features.card_2_title'),
                        'card_2_body' => __('procynia.public.features.card_2_body'),
                        'card_3_title' => __('procynia.public.features.card_3_title'),
                        'card_3_body' => __('procynia.public.features.card_3_body'),
                        'card_4_title' => __('procynia.public.features.card_4_title'),
                        'card_4_body' => __('procynia.public.features.card_4_body'),
                        'card_5_title' => __('procynia.public.features.card_5_title'),
                        'card_5_body' => __('procynia.public.features.card_5_body'),
                        'card_6_title' => __('procynia.public.features.card_6_title'),
                        'card_6_body' => __('procynia.public.features.card_6_body'),
                    ],
                    'pricing' => [
                        'title' => __('procynia.public.pricing.title'),
                        'lead' => __('procynia.public.pricing.lead'),
                        'note' => __('procynia.public.pricing.note'),
                        'card_1_title' => __('procynia.public.pricing.card_1_title'),
                        'card_1_body' => __('procynia.public.pricing.card_1_body'),
                        'card_2_title' => __('procynia.public.pricing.card_2_title'),
                        'card_2_body' => __('procynia.public.pricing.card_2_body'),
                        'card_3_title' => __('procynia.public.pricing.card_3_title'),
                        'card_3_body' => __('procynia.public.pricing.card_3_body'),
                    ],
                    'security' => [
                        'title' => __('procynia.public.security.title'),
                        'lead' => __('procynia.public.security.lead'),
                        'card_1_title' => __('procynia.public.security.card_1_title'),
                        'card_1_body' => __('procynia.public.security.card_1_body'),
                        'card_2_title' => __('procynia.public.security.card_2_title'),
                        'card_2_body' => __('procynia.public.security.card_2_body'),
                        'card_3_title' => __('procynia.public.security.card_3_title'),
                        'card_3_body' => __('procynia.public.security.card_3_body'),
                        'card_4_title' => __('procynia.public.security.card_4_title'),
                        'card_4_body' => __('procynia.public.security.card_4_body'),
                    ],
                    'contact' => [
                        'title' => __('procynia.public.contact.title'),
                        'lead' => __('procynia.public.contact.lead'),
                        'note' => __('procynia.public.contact.note'),
                        'sales_label' => __('procynia.public.contact.sales_label'),
                        'support_label' => __('procynia.public.contact.support_label'),
                        'privacy_label' => __('procynia.public.contact.privacy_label'),
                        'general_label' => __('procynia.public.contact.general_label'),
                        'phone_label' => __('procynia.public.contact.phone_label'),
                    ],
                    'terms' => [
                        'title' => __('procynia.public.terms.title'),
                        'lead' => __('procynia.public.terms.lead'),
                        'notice' => __('procynia.public.terms.notice'),
                        'item_1_title' => __('procynia.public.terms.item_1_title'),
                        'item_1_body' => __('procynia.public.terms.item_1_body'),
                        'item_2_title' => __('procynia.public.terms.item_2_title'),
                        'item_2_body' => __('procynia.public.terms.item_2_body'),
                        'item_3_title' => __('procynia.public.terms.item_3_title'),
                        'item_3_body' => __('procynia.public.terms.item_3_body'),
                        'item_4_title' => __('procynia.public.terms.item_4_title'),
                        'item_4_body' => __('procynia.public.terms.item_4_body'),
                    ],
                    'privacy' => [
                        'title' => __('procynia.public.privacy.title'),
                        'lead' => __('procynia.public.privacy.lead'),
                        'notice' => __('procynia.public.privacy.notice'),
                        'item_1_title' => __('procynia.public.privacy.item_1_title'),
                        'item_1_body' => __('procynia.public.privacy.item_1_body'),
                        'item_2_title' => __('procynia.public.privacy.item_2_title'),
                        'item_2_body' => __('procynia.public.privacy.item_2_body'),
                        'item_3_title' => __('procynia.public.privacy.item_3_title'),
                        'item_3_body' => __('procynia.public.privacy.item_3_body'),
                        'item_4_title' => __('procynia.public.privacy.item_4_title'),
                        'item_4_body' => __('procynia.public.privacy.item_4_body'),
                    ],
                    'register' => [
                        'title' => __('procynia.public.register.title'),
                        'lead' => __('procynia.public.register.lead'),
                        'notice' => __('procynia.public.register.notice'),
                        'item_1_title' => __('procynia.public.register.item_1_title'),
                        'item_1_body' => __('procynia.public.register.item_1_body'),
                        'item_2_title' => __('procynia.public.register.item_2_title'),
                        'item_2_body' => __('procynia.public.register.item_2_body'),
                        'item_3_title' => __('procynia.public.register.item_3_title'),
                        'item_3_body' => __('procynia.public.register.item_3_body'),
                    ],
                    'registration' => [
                        'success' => __('procynia.public.registration.success'),
                        'failure' => __('procynia.public.registration.failure'),
                        'form' => [
                            'title' => __('procynia.public.registration.form.title'),
                            'lead' => __('procynia.public.registration.form.lead'),
                            'business_only' => __('procynia.public.registration.form.business_only'),
                            'company_section' => __('procynia.public.registration.form.company_section'),
                            'owner_section' => __('procynia.public.registration.form.owner_section'),
                            'legal_section' => __('procynia.public.registration.form.legal_section'),
                            'company_name' => __('procynia.public.registration.form.company_name'),
                            'company_name_help' => __('procynia.public.registration.form.company_name_help'),
                            'nationality_id' => __('procynia.public.registration.form.nationality_id'),
                            'nationality_id_help' => __('procynia.public.registration.form.nationality_id_help'),
                            'language_id' => __('procynia.public.registration.form.language_id'),
                            'language_id_help' => __('procynia.public.registration.form.language_id_help'),
                            'owner_name' => __('procynia.public.registration.form.owner_name'),
                            'owner_name_help' => __('procynia.public.registration.form.owner_name_help'),
                            'owner_email' => __('procynia.public.registration.form.owner_email'),
                            'owner_email_help' => __('procynia.public.registration.form.owner_email_help'),
                            'password' => __('procynia.public.registration.form.password'),
                            'password_help' => __('procynia.public.registration.form.password_help'),
                            'privacy_accepted' => __('procynia.public.registration.form.privacy_accepted'),
                            'terms_accepted' => __('procynia.public.registration.form.terms_accepted'),
                            'represents_business' => __('procynia.public.registration.form.represents_business'),
                            'submit' => __('procynia.public.registration.form.submit'),
                            'already_have_account' => __('procynia.public.registration.form.already_have_account'),
                            'sign_in' => __('procynia.public.registration.form.sign_in'),
                            'privacy_link' => __('procynia.public.registration.form.privacy_link'),
                            'terms_link' => __('procynia.public.registration.form.terms_link'),
                        ],
                    ],
                ],
                'knowledge_show' => __('procynia.knowledge_show'),
                'knowledge_duplicate' => __('procynia.knowledge_duplicate'),
                'users_form' => [
                    'no_departments' => __('procynia.users_form.no_departments'),
                    'create_title' => __('procynia.users_form.create_title'),
                    'create_subtitle' => __('procynia.users_form.create_subtitle'),
                    'edit_title' => __('procynia.users_form.edit_title'),
                    'edit_subtitle' => __('procynia.users_form.edit_subtitle'),
                    'field_name' => __('procynia.users_form.field_name'),
                    'field_email' => __('procynia.users_form.field_email'),
                    'field_role' => __('procynia.users_form.field_role'),
                    'field_password' => __('procynia.users_form.field_password'),
                    'field_new_password' => __('procynia.users_form.field_new_password'),
                    'field_confirm_password' => __('procynia.users_form.field_confirm_password'),
                    'field_confirm_new_password' => __('procynia.users_form.field_confirm_new_password'),
                    'field_status' => __('procynia.users_form.field_status'),
                    'role_help_create' => __('procynia.users_form.role_help_create'),
                    'role_help_edit' => __('procynia.users_form.role_help_edit'),
                    'role_locked_create' => __('procynia.users_form.role_locked_create'),
                    'role_locked_edit' => __('procynia.users_form.role_locked_edit'),
                    'system_owner_notice' => __('procynia.users_form.system_owner_notice'),
                    'admin_scope_label' => __('procynia.users_form.admin_scope_label'),
                    'admin_scope_help' => __('procynia.users_form.admin_scope_help'),
                    'admin_scope_locked' => __('procynia.users_form.admin_scope_locked'),
                    'admin_scope_none' => __('procynia.users_form.admin_scope_none'),
                    'admin_scope_not_set' => __('procynia.users_form.admin_scope_not_set'),
                    'password_hint' => __('procynia.users_form.password_hint'),
                    'password_empty_hint' => __('procynia.users_form.password_empty_hint'),
                    'email_readonly_hint' => __('procynia.users_form.email_readonly_hint'),
                    'departments_label' => __('procynia.users_form.departments_label'),
                    'departments_help' => __('procynia.users_form.departments_help'),
                    'managed_departments_label' => __('procynia.users_form.managed_departments_label'),
                    'managed_departments_help' => __('procynia.users_form.managed_departments_help'),
                    'primary_affiliation_label' => __('procynia.users_form.primary_affiliation_label'),
                    'primary_affiliation_help' => __('procynia.users_form.primary_affiliation_help'),
                    'primary_department_label' => __('procynia.users_form.primary_department_label'),
                    'primary_department_option' => __('procynia.users_form.primary_department_option'),
                    'primary_department_help' => __('procynia.users_form.primary_department_help'),
                    'status_active_on_create' => __('procynia.users_form.status_active_on_create'),
                    'active' => __('procynia.users_form.active'),
                    'inactive' => __('procynia.users_form.inactive'),
                    'own_account' => __('procynia.users_form.own_account'),
                    'deactivate' => __('procynia.users_form.deactivate'),
                    'activate' => __('procynia.users_form.activate'),
                    'deactivating' => __('procynia.users_form.deactivating'),
                    'activating' => __('procynia.users_form.activating'),
                    'saving' => __('procynia.users_form.saving'),
                    'create_button' => __('procynia.users_form.create_button'),
                    'save_button' => __('procynia.users_form.save_button'),
                    'cannot_deactivate_self' => __('procynia.users_form.cannot_deactivate_self'),
                    'contributor_locked_role' => __('procynia.users_form.contributor_locked_role'),
                    'hint_role' => __('procynia.users_form.hint_role'),
                    'hint_user_license' => __('procynia.users_form.hint_user_license'),
                    'hint_admin_scope' => __('procynia.users_form.hint_admin_scope'),
                ],
                'customer_env' => [
                    'title' => __('procynia.customer_env.title'),
                    'subtitle' => __('procynia.customer_env.subtitle'),
                    'tab_departments' => __('procynia.customer_env.tab_departments'),
                    'tab_users' => __('procynia.customer_env.tab_users'),
                    'tab_permissions' => __('procynia.customer_env.tab_permissions'),
                    'show' => __('procynia.customer_env.show'),
                    'hide' => __('procynia.customer_env.hide'),
                    'dept_heading' => __('procynia.customer_env.dept_heading'),
                    'dept_subtitle' => __('procynia.customer_env.dept_subtitle'),
                    'create_dept' => __('procynia.customer_env.create_dept'),
                    'no_create_dept_hint' => __('procynia.customer_env.no_create_dept_hint'),
                    'col_name' => __('procynia.customer_env.col_name'),
                    'col_description' => __('procynia.customer_env.col_description'),
                    'col_users' => __('procynia.customer_env.col_users'),
                    'col_status' => __('procynia.customer_env.col_status'),
                    'col_updated' => __('procynia.customer_env.col_updated'),
                    'col_actions' => __('procynia.customer_env.col_actions'),
                    'active' => __('procynia.customer_env.active'),
                    'inactive' => __('procynia.customer_env.inactive'),
                    'edit' => __('procynia.customer_env.edit'),
                    'deactivate' => __('procynia.customer_env.deactivate'),
                    'activate' => __('procynia.customer_env.activate'),
                    'deactivating' => __('procynia.customer_env.deactivating'),
                    'activating' => __('procynia.customer_env.activating'),
                    'no_edit_dept_hint' => __('procynia.customer_env.no_edit_dept_hint'),
                    'no_depts_title' => __('procynia.customer_env.no_depts_title'),
                    'no_depts_hint' => __('procynia.customer_env.no_depts_hint'),
                    'users_heading' => __('procynia.customer_env.users_heading'),
                    'users_subtitle' => __('procynia.customer_env.users_subtitle'),
                    'create_user' => __('procynia.customer_env.create_user'),
                    'search_label' => __('procynia.customer_env.search_label'),
                    'search_placeholder' => __('procynia.customer_env.search_placeholder'),
                    'dept_filter_label' => __('procynia.customer_env.dept_filter_label'),
                    'all_depts' => __('procynia.customer_env.all_depts'),
                    'status_filter_label' => __('procynia.customer_env.status_filter_label'),
                    'all_statuses' => __('procynia.customer_env.all_statuses'),
                    'active_status' => __('procynia.customer_env.active_status'),
                    'inactive_status' => __('procynia.customer_env.inactive_status'),
                    'col_email' => __('procynia.customer_env.col_email'),
                    'col_role' => __('procynia.customer_env.col_role'),
                    'col_departments' => __('procynia.customer_env.col_departments'),
                    'created_prefix' => __('procynia.customer_env.created_prefix'),
                    'user_member_of' => __('procynia.customer_env.user_member_of'),
                    'admin_scope' => __('procynia.customer_env.admin_scope'),
                    'full_env' => __('procynia.customer_env.full_env'),
                    'full_company' => __('procynia.customer_env.full_company'),
                    'no_department' => __('procynia.customer_env.no_department'),
                    'no_departments' => __('procynia.customer_env.no_departments'),
                    'no_users_title' => __('procynia.customer_env.no_users_title'),
                    'no_users_hint' => __('procynia.customer_env.no_users_hint'),
                    'inactive_depts_label' => __('procynia.customer_env.inactive_depts_label'),
                    'own_account' => __('procynia.customer_env.own_account'),
                    'modal_dept_description' => __('procynia.customer_env.modal_dept_description'),
                    'modal_dept_edit_title' => __('procynia.customer_env.modal_dept_edit_title'),
                    'modal_dept_create_title' => __('procynia.customer_env.modal_dept_create_title'),
                    'field_name' => __('procynia.customer_env.field_name'),
                    'field_description' => __('procynia.customer_env.field_description'),
                    'cancel' => __('procynia.customer_env.cancel'),
                    'saving' => __('procynia.customer_env.saving'),
                    'save_dept' => __('procynia.customer_env.save_dept'),
                    'permissions_heading' => __('procynia.customer_env.permissions_heading'),
                    'permissions_subtitle' => __('procynia.customer_env.permissions_subtitle'),
                    'col_action' => __('procynia.customer_env.col_action'),
                ],
                'auth' => [
                    'email' => __('procynia.user.email'),
                    'password' => __('procynia.user.password'),
                    'remember' => __('procynia.frontend.remember_me'),
                    'sign_in' => __('procynia.frontend.sign_in'),
                    'title' => __('procynia.frontend.sign_in_title'),
                    'subtitle' => __('procynia.frontend.sign_in_subtitle'),
                ],
            ],
        ]);
    }
}
